name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing IDQ server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ec2-52-43-172-154.us-west-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Hi"
 

